name: "Terraform CKA Lab VMs"

on:
  push:
    branches: ["*"]
    paths:
      - 'proxmox/terraform/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  plan:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: proxmox/terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set Terraform Variables
        run: |
          echo "TF_VAR_SV3_URL=${{ vars.SV3_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_SV3_TOKEN_ID=${{ vars.SV3_TOKEN_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_SV3_TOKEN_SECRET=${{ secrets.SV3_TOKEN_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_PUBLIC_SSH_KEY=${{ secrets.PUBLIC_SSH_KEY }}" >> $GITHUB_ENV

      - name: Check Proxmox connectivity
        run: |
          curl -k -s -o /dev/null -w "%{http_code}" $TF_VAR_SV3_URL || echo "Cannot connect to Proxmox"

      - name: Tofu Init
        run: tofu init

      - name: Tofu Plan
        run: tofu plan -detailed-exitcode
        timeout-minutes: 5
        env:
          TF_LOG: TRACE

  apply:
    runs-on: self-hosted
    needs: plan
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: proxmox/terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Set Terraform Variables
        run: |
          echo "TF_VAR_SV3_URL=${{ vars.SV3_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_SV3_TOKEN_ID=${{ vars.SV3_TOKEN_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_SV3_TOKEN_SECRET=${{ secrets.SV3_TOKEN_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_PUBLIC_SSH_KEY=${{ secrets.PUBLIC_SSH_KEY }}" >> $GITHUB_ENV

      - name: Tofu Init
        run: tofu init

      - name: Tofu Apply
        run: tofu apply -auto-approve
